const projects = [
  {
    id: 1,
    category: "UI/UX",
    image: "/images/project1.jpg",
    title: "Project Title One (UI/UX)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: 2,
    category: "Frontend",
    image: "/images/project2.jpg",
    title: "Project Title Two (Frontend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: 3,
    category: "Frontend",
    image: "/images/project3.jpg",
    title: "Project Title Three (Frontend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: 4,
    category: "UI/UX",
    image: "/images/project4.jpg",
    title: "Project Title Four (UI/UX)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: 5,
    category: "UI/UX",
    image: "/images/project5.jpg",
    title: "Project Title Five (UI/UX)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! ",
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: 6,
    category: "Frontend",
    image: "/images/project6.jpg",
    title: "Project Title Six (Frontend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: 7,
    category: "Frontend",
    image: "/images/project7.jpg",
    title: "Project Title Seven (Frontend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: 8,
    category: "Backend",
    image: "/images/project8.jpg",
    title: "Project Title Eight (Backend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demoLink: "#",
    githubLink: "#",
  },
  {
    id: 9,
    category: "Frontend",
    image: "/images/project9.jpg",
    title: "Project Title Nine (Frontend)",
    desc: "Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut!",
    demoLink: "#",
    githubLink: "#",
  },
];

const categories = projects.map((item) => item.category);
const categoryOptions = ["All", ...new Set(categories)];

export { projects, categories, categoryOptions };
